# Generated by Django 3.1.7 on 2021-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filmini',
            fields=[
                ('title', models.CharField(help_text='Enter field documentation', max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagline', models.TextField()),
                ('overview', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('revenue', models.IntegerField()),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('original_language', models.CharField(max_length=2)),
                ('budget', models.IntegerField()),
                ('runtime', models.IntegerField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
