# Generated by Django 3.1.7 on 2021-03-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_filmini_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filmini',
            table='filmini',
        ),
    ]
