# Generated by Django 3.1.7 on 2021-03-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210304_1456'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filmini',
            table=None,
        ),
    ]
