# Generated by Django 3.1.7 on 2021-03-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210304_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmini',
            name='status',
            field=models.CharField(default='def_error', max_length=10),
        ),
        migrations.AlterModelTable(
            name='filmini',
            table='catalog_filmini',
        ),
    ]
